auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("category/", views.categories, name="categories"),
    path("sell/", views.sell, name="sell"),
    path("auction/<int:auction_id>/", views.auction, name="auction"),
    path("category/<str:filter>/", views.filter, name="filter"),
    path("wishlist/", views.wishlist, name="wishlist"),
    path("myauctions/", views.myAuctions, name="myauctions"),
    path("auction/<int:auction_id>/bids", views.auction_bids, name="auction_bids")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from . import utils

class User(AbstractUser):
    # def __str__(self):
    #     return f"{self.username} - id = {self.pk}"
    pass


class Category(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"
    
    
class Auction(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller")
    title = models.CharField(max_length=32)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="category")
    description = models.TextField(max_length=1200)
    creation_date = models.DateTimeField(auto_now_add=True, null=True)
    start_bid = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    bid = models.DecimalField(default=0.00, max_digits=10, decimal_places=2, null=True)
    bid_counter = models.IntegerField(default=0)
    active = models.BooleanField(default=True)
    close_date = models.DateTimeField(auto_now_add=True, null=True)
    winner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, related_name="auction_winner")

    class Meta:
        ordering = ["creation_date"]

    def __str__(self):
        return f"{self.title} by {self.seller}"
    
class ImagesUpload(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, related_name="seller_img")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction_img", null=True)
    upload = models.FileField(upload_to=utils.user_directory_path, null=True)

    def __str__(self):
        return f"{self.upload} for {self.auction} by {self.seller}"
    

class Bid(models.Model):
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bidder")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction_bid")
    bid_date = models.DateTimeField(auto_now_add=True, null=True)
    bid = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        ordering = ["bid_date"]

    def __str__(self):
        return f"{self.bid} on {self.auction} by {self.bidder}"
    

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="wishlist_user")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="wishlist_auction")
    wishlist_date = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ["wishlist_date"]

    def __str__(self):
        return f"{self.user} wishlisted {self.auction}"
    

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_user")
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="comment_auction")
    comment = models.TextField(max_length=1200)
    comment_date = models.DateTimeField(auto_now_add=True, null=True)

    class Meta:
        ordering = ["comment_date"]

    def __str__(self):
        return f"{self.user} comment on {self.auction}"

auctions/forms.py
from django import forms

from . import utils

class SellForm(forms.Form):
    title = forms.CharField(label="TITLE", required=True, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Title", "autocomplete": "off"}))
    category = forms.ChoiceField(label="CATEGORY", required=True, choices=utils.all_categories())
    description = forms.CharField(label="DESCRIPTION", required=True, widget=forms.Textarea(attrs={"placeholder": "Write a detailed description of your item"}))
    starting_bid = forms.DecimalField(label="STARTING PRICE", required=True, widget=forms.NumberInput(attrs={"min": 1, "class": "form-control", "placeholder": "$", "autocomplete": "off"}))


class BidForm(forms.Form):
    bid = forms.DecimalField(label=False, widget=forms.NumberInput(attrs={"min": 1, "class": "form-control", "placeholder": "$", "autocomplete": "off"}))


class CommentForm(forms.Form):
    comment = forms.CharField(label=False, widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Comment here", "autocomplete": "off"}))

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Q

from .models import User, Category, Auction, ImagesUpload, Bid, Wishlist, Comment
from .forms import SellForm, BidForm, CommentForm
from .utils import *


def index(request):
    trending = Auction.objects.filter(active=True).order_by("-bid_counter")[:4]
    new = Auction.objects.filter(active=True).order_by("-creation_date")[:4]
    images = getFirstImage(ImagesUpload.objects.all())

    return render(request, "auctions/index.html", {
        "trending": trending,
        "new": new,
        "images": images
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")


def categories(request):
    # Get first image for each auction
    images = getFirstImage(ImagesUpload.objects.all())
    
    return render(request, "auctions/categories.html", {
        "all": "All",
        "category": "ALL",
        "categories": Category.objects.all(),
        "auctions": Auction.objects.filter(active=True).order_by('?'),
        "images": images
    })


def filter(request, filter):
    # Get first image for each auction
    images = getFirstImage(ImagesUpload.objects.all())

    if filter == "all":
        return categories(request)
    
    return render(request, "auctions/categories.html", {
        "all": "All",
        "category": filter,
        "categories": Category.objects.all(),
        "auctions": Auction.objects.filter(active=True, category=Category.objects.get(name=filter)),
        "images": images
    })
    

def sell(request):
    sell_form = SellForm()

    # POST REQUESTS 
    if request.method == "POST":
        # get informations form form
        sell_form_data = SellForm(request.POST)
        if sell_form_data.is_valid():
            title = sell_form_data.cleaned_data["title"]
            category = sell_form_data.cleaned_data["category"]
            description = sell_form_data.cleaned_data["description"]
            starting_bid = sell_form_data.cleaned_data["starting_bid"]

            # Create auction into model
            new_auction = Auction(
                seller = request.user,
                title = title,
                category = Category.objects.get(pk = category),
                description = description,
                start_bid = starting_bid
            )
            new_auction.save()

            # Save imported images into model
            for image in request.FILES.getlist("img-upload"):
                new_img = ImagesUpload(
                    seller = request.user,
                    auction = new_auction,
                    upload = image
                )
                new_img.save()

            # Redirect to index
            return HttpResponseRedirect(reverse("auctions:index"))

    # GET REQUESTS
    return render(request, "auctions/sell.html", {
        "sell_form": sell_form,
    })


def auction(request, auction_id):
    bid_form = BidForm()
    comment_form = CommentForm()
    current_auction = Auction.objects.get(pk=auction_id)
    comments = Comment.objects.filter(auction=current_auction)
    images = ImagesUpload.objects.filter(auction=current_auction)

    # Defined if current auction is user's or not
    closeButton = isUserAuction(request.user, current_auction.pk)

    default_context = {
        "wishlist": "Add To Wishlist",
    }
   
    # Check user wishlist
    if request.user.is_authenticated: 
        is_wishlisted = Wishlist.objects.filter(user=request.user, auction=current_auction)

        if is_wishlisted:
            default_context = {
                    "wishlist": "Remove From Wishlist"
            }
            
            highest_bid = Bid.objects.filter(auction=current_auction).order_by('-bid').first()

            if highest_bid and request.user == highest_bid.bidder:
                default_context['message'] = "You currently got the highest bid !"


    # Check if current auction is user's and replace wishlist button into close auction button
    if request.method == "GET" and isUserAuction(request.user, current_auction.pk):
        default_context = {
            "closeButton": closeButton,
            "closeMessage": "Close Auction"
        }

    context = default_context.copy()

    # POST REQUESTS
    if request.method == "POST":
        # For any POST request user is ask to login of register
        if not request.user.is_authenticated: 
            return render(request, "auctions/login.html")
        else:   
            # Wishlist auction
            if "wishlist" in request.POST:
                context = handle_wishlisting(request, current_auction, is_wishlisted)
            #  Bid auction
            elif "bid" in request.POST:
                # Get bid informations from form
                bid_form_data = BidForm(request.POST)
                context = handle_bidding(request, current_auction, is_wishlisted, bid_form_data, context)
            # Close auction
            elif "close" in request.POST:
                context = handle_auction_closing(request, current_auction, closeButton)
            # Comment auction
            elif "comment" in request.POST:
                comment_form_data = CommentForm(request.POST)
                handle_commenting(request, current_auction, comment_form_data)
                       
    # GET REQUESTS
    return render(request, "auctions/auction.html", {
        "bid_form": bid_form,
        "auction": current_auction,
        "comment_form": comment_form,
        "comments": comments,
        "images": images,
        "active": current_auction.active,
        "context": context
    })

        
def wishlist(request):
    # Get all on going wishlisted auctions
    on_going_wishlist = Wishlist.objects.filter(Q(user=request.user) & Q(auction__active=True))

    # Get all won auctions
    won_wishlist = Auction.objects.filter(active=False, winner=request.user)

    # Get all lost auctions 
    lost_items = Bid.objects.filter(Q(bidder=request.user) & Q(auction__active=False) & ~Q(auction__winner=request.user)).order_by().values_list('auction', flat=True).distinct()
    
    lost_wishlist = []
    for auction_id in lost_items:
        lost_wishlist.append(Auction.objects.get(pk=auction_id))

    images = getFirstImage(ImagesUpload.objects.all())

    return render(request, "auctions/wishlist.html", {
        "ongoing": on_going_wishlist,
        "won": won_wishlist,
        "lost": lost_wishlist,
        "images": images
    })


def myAuctions(request):
    # Get all active auctions posted by current user
    my_active_auctions = Auction.objects.filter(seller=request.user, active=True)
    # Get all non-active auctions posted by current user
    my_closed_auctions = Auction.objects.filter(seller=request.user, active=False)
    # Get auctions images
    images = getFirstImage(ImagesUpload.objects.all())

    return render(request, 'auctions/my_auctions.html', {
        "active": my_active_auctions,
        "closed": my_closed_auctions,
        "images": images
    })


def auction_bids(request, auction_id):
    current_auction = Auction.objects.get(pk=auction_id)
    all_auction_bid = Bid.objects.filter(auction=current_auction).order_by('-bid')

    return render(request, 'auctions/auction_bids.html', {
        "auction": current_auction,
        "bids": all_auction_bid,
    })

auctions/templates/auctions/auction.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="auction-container flex">
    <div class="auction">
        <div class="auction-images">
            <div class="auction-images-big flex">
                <img src="{{ images.first.upload.url }}" alt="{{ images.first.upload.url.first }}">
            </div>
            <div class="auction-images-small flex">
                {% for image in images %}
                <img src="{{ image.upload.url }}" alt="{{ image.upload.url }}" class="small-img">
                {% endfor %}
            </div>
        </div>
        <div class="auction-bid-container flex">
            <div class="auction-bid flex">
                <h1>{{ auction.title }}</h1>
                <div class="auction-bid-details flex">
                    {% if auction.bid_counter == 0 %}
                    <div class="auction-current-bid">{{ auction.start_bid|floatformat:2 }} $</div>
                    {% else %}
                    <div class="auction-current-bid">{{ auction.bid|floatformat:2 }} $</div>
                    {% endif %}
                    <a href="{% url 'auctions:auction_bids' auction.pk %}">
                        <div class="auction-bid-counter">
                            {% if auction.bid_counter == 0 %}
                            <p>No bids yet</p>
                            {% elif auction.bid_counter == 1 %}
                            <p>{{ auction.bid_counter }} bid</p>
                            {% else %}
                            <p>{{ auction.bid_counter }} bids</p>
                            {% endif %}
                        </div>
                    </a>
                </div>
                <div class="auction-forms">
                    <div class="bid-form">
                        <form action="{% url 'auctions:auction' auction.pk %}" method="POST"
                            class="auction-bid-form flex">
                            {% csrf_token %}
                            {{ bid_form }}
                            {% if active and user != auction.seller %}
                            <input type="submit" value="Place Bid" class="btn">
                            {% else %}
                            <input type="submit" value="Place Bid" class="btn btn-disable" disabled>
                            {% endif %}
                        </form>
                    </div>
                    {% if context.closeButton %}
                    <div class="wishlist-form">
                        <form action="{% url 'auctions:auction' auction.pk %}" method="POST"
                            class="auction-wishlist-form flex">
                            {% csrf_token %}
                            {% if active %}
                            <input type="submit" name="close" value="Close Auction" class="btn">
                            {% else %}
                            <input type="submit" name="close" value="Closed" class="btn btn-disable" disabled>
                            {% endif %}
                        </form>
                    </div>
                    {% else %}
                    <div class="wishlist-form">
                        <form action="{% url 'auctions:auction' auction.pk %}" method="POST"
                            class="auction-wishlist-form flex">
                            {% csrf_token %}
                            {% if active %}
                            <input type="submit" name="wishlist" value="{{ context.wishlist }}" class="btn">
                            {% else %}
                            <input type="submit" name="wishlist" value="{{ context.wishlist }}" class="btn btn-disable"
                                disabled>
                            {% endif %}
                        </form>
                    </div>
                    {% endif %}
                </div>

            </div>
            <div class="auction-msg">
                {% if not active and user == auction.winner %}
                <div class="error-msg">Congratulation ! This auction is now yours.</div>
                {% elif not active and user != auction.winner and user != auction.seller %}
                <div class="error-msg">Unfortunatly, someone else won this auction.</div>
                {% elif not active and user != auction.winner and user == auction.seller %}
                <div class="error-msg">This auction has ended.</div>
                {% else %}
                <div class="error-msg">{{ context.message }}</div>
                {% endif %}
            </div>
        </div>
    </div>
    <h2>DETAILS</h2>
    <div class="auction-details flex">
        <div class="auction-description auction-detail">
            <p class="auction-label">Description</p>
            <p class="auction-content">{{ auction.description|linebreaksbr }}</p>
        </div>
        <div class="auction-category auction-detail">
            <p class="auction-label">Category</p>
            <p class="auction-content">{{ auction.category }}</p>
        </div>
        <div class="auction-seller auction-detail">
            <p class="auction-label">Seller</p>
            <p class="auction-content">{{ auction.seller }}</p>
        </div>
        <div class="auction-creation-date auction-detail">
            <p class="auction-label">Online since</p>
            <p class="auction-content">{{ auction.creation_date }}</p>
        </div>
    </div>
    <h2>COMMENTS</h2>
    <div class="comment-container">
        {% include "./comment.html" %}
    </div>
</div>

<script>
    const auctionImagesBig = document.querySelector(".auction-images-big")
    const smallImg = document.querySelectorAll(".small-img")

    const displayImage = (e) => {
        let bigImages = ""
        bigImages = `<img src="${e.currentTarget.src}" alt="${e.currentTarget.src}">`
        auctionImagesBig.innerHTML = bigImages;
    }

    smallImg.forEach(e => {
        e.addEventListener('mouseover', displayImage)
    });
</script>
{% endblock %}

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
<div class="categories">
    <h1>{{ category|upper }}</h1>
    <ul class="nav-categories flex">
        <a class="nav-categories-link" href="{% url 'auctions:categories' %}">
            <li class="nav-categories-item">{{ all }}</li>
        </a>
        {% for category in categories %}
        <a class="nav-categories-link" href="{% url 'auctions:filter' category %}">
            <li class="nav-categories-item">{{ category }}</li>
        </a>
        {% endfor %}
    </ul>
    {% if auctions %}
    <div class="items-container">
        {% for auction in auctions %}
        {% include "./item.html" %}
        {% endfor %}
    </div>
    {% else %}
    <div class="no-items">
        <h2>Unfortunatly, there is no items for this category yet.</h2>
        {% if user.is_authenticated %}
        <p>Want to sell something ? Please click <a href="{% url 'auctions:sell' %}">HERE</a></p>
        {% else %}
        <p>Want to sell something ? <a href="{% url 'auctions:login' %}">Sign In</a> and start selling.</p>
        {% endif %}
    </div>
    {% endif %}
</div>


{% endblock %}

auctions/templates/auctions/comment.html
<div class="comment-display">
    {% for comment in comments %}
    <div class="comment">
        <p>{{ comment.comment }}</p>
    </div>
    <div class="comment-details">
        <p>{{ comment.user }} - {{ comment.comment_date }}</p>
    </div>
    {% endfor %}
</div>
<div class="comment-form">
    <form action="{% url 'auctions:auction' auction.pk %}" method="POST" class="auction-wishlist-form flex">
        {% csrf_token %}
        {{ comment_form }}
        {% if active %}
        <input type="submit" value="Comment" class="btn">
        {% else %}
        <input type="submit" value="Comment" class="btn btn-disable" disabled>
        {% endif %}
    </form>
</div>

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}
{% load static %}
{% block body %}
<div class="home-container">
    <h2>HOME</h2>
    <div class="banner-grid">
        <a href="{% url 'auctions:filter' 'Home & Garden' %}" class="image-container banner-homegarden">
            <img src="{% static 'auctions/images/homegarden.jpg' %}" class="banner-grid-img">
            <p>HOME<br>&<br>GARDEN</p>
        </a>
        <a href="{% url 'auctions:filter' 'Computers' %}" class="image-container banner-computer">
            <img src="{% static 'auctions/images/computer.jpg' %}" class="banner-grid-img">
            <p>COMPUTER</p>
        </a>
        <a href="{% url 'auctions:filter' 'Sport' %}" class="image-container banner-sport">
            <img src="{% static 'auctions/images/sport.jpg' %}" class="banner-grid-img">
            <p>SPORT</p>
        </a>
    </div>
    <h2>NEW</h2>
    <div class="items-container">
        {% for auction in new %}
        {% include "./item.html" %}
        {% endfor %}
    </div>
    <h2>TRENDING</h2>
    <div class="items-container">
        {% for auction in trending %}
        {% include "./item.html" %}
        {% endfor %}
    </div>
    <h2>VIDEO GAMES</h2>
    <div class="banner-video-game">
        <img src="{% static 'auctions/images/pexels-cottonbro-studio-3945663.jpg' %}"
            alt="pexels-cottonbro-studio-3945655.jpg" class="banner-image">
        <form method="POST" action="{% url 'auctions:filter' 'Video Games' %}" class="banner-form">
            {% csrf_token %}
            <input type="submit" value="Discover our gaming items" class="banner-btn">
        </form>
    </div>

</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>{% block title %}eBuy{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="icon" href="data:,">
</head>

<body>
    <div class="wrapper flex">
        <div class="navbar">
            <div class="navbar-head flex">
                <h1><a href="{% url 'auctions:index' %}">eBuy</a></h1>
                <div class="authentication flex">
                    {% if user.is_authenticated %}
                    <p>Signed in as <strong>{{ user.username }}</strong>.</p>
                    {% else %}
                    <p>Not signed in.</p>
                    {% endif %}
                    <input type="checkbox" id="auth-collapse-head">
                    <label for="auth-collapse-head">
                        <i class="fa-solid fa-circle-user"></i>
                    </label>
                    <div class="auth-collapse-content flex">
                        <i class="fa-solid fa-chevron-up"></i>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                        </li>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="navbar-links">
                <ul class="nav flex">
                    <li class="nav-item-page">
                        <a class="nav-link-page" href="{% url 'auctions:index' %}">Home</a>
                    </li>
                    <li class="nav-item-page">
                        <a class="nav-link-page" href="{% url 'auctions:categories' %}">Categories</a>
                    </li>

                    {% if user.is_authenticated %}
                    <li class="nav-item-page">
                        <a class="nav-link-page" href="{% url 'auctions:sell' %}">Sell</a>
                    </li>
                    <li class="nav-item-page">
                        <a class="nav-link-page" href="{% url 'auctions:wishlist' %}">Wishlist</a>
                    </li>
                    <li class="nav-item-page">
                        <a class="nav-link-page" href="{% url 'auctions:myauctions' %}">My Auctions</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>

        <div class="container">
            {% block body %}
            {% endblock %}
        </div>

        <div class="flex footer">
            <p><a href="https://cs50.harvard.edu/web/2020/projects/2/commerce/" target="_blank">Project 2 - Commerce</a>
            </p>
            <p><a href="https://www.youtube.com/watch?v=Nn7EX3zkGUo&list=PLhQjrBD2T380xvFSUmToMMzERZ3qB5Ueu"
                    target="_blank">CS50’s Web Programming with Python and JavaScript</a></p>
            <p>Created by <a href="https://github.com/odakris?tab=repositories" target="_blank">odakris</a></p>
        </div>
    </div>
</body>

</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="connection flex">
    <h2>Login</h2>

    <form action="{% url 'auctions:login' %}" method="post" class="connection-form">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn" type="submit" value="Login">
    </form>

    <p>Don't have an account ? <a href="{% url 'auctions:register' %}">Register here</a></p>

    {% if message %}
    <div class="error-msg">{{ message }}</div>
    {% endif %}

    <div class="logins">
        <h3>Demo Account n°1</h3>
        <div class="login flex">
            <div class="login-title flex">
                <p>Username: </p>
                <p>Password: </p>
            </div>
            <div class="login-data flex">
                <p>cla</p>
                <p>cla</p>
            </div>
        </div>
        <h3>Demo Account n°2</h3>
        <div class="login flex">
            <div class="login-title flex">
                <p>Username: </p>
                <p>Password: </p>
            </div>
            <div class="login-data flex">
                <p>toytoy</p>
                <p>toytoy</p>
            </div>
        </div>
    </div>

</div>


{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

<div class="connection flex">
    <h2>Register</h2>

    <form action="{% url 'auctions:register' %}" method="post" class="connection-form">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn" type="submit" value="Register">
    </form>

    <p>Already have an account ? <a href="{% url 'auctions:login' %}">Log In here</a></p>

    {% if message %}
    <div class="error-msg">{{ message }}</div>
    {% endif %}
</div>


{% endblock %}